/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerInfo {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface Enquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'customerInfo' : CustomerInfo,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'name' : string,
  'priceInInr' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : ProductCategory,
}
export type ProductCategory = { 'customisation' : null } |
  { 'consumerElectronics' : null } |
  { 'laserEngraving' : null } |
  { 'threeDPrinting' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, ProductCategory],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initSampleProducts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, CustomerInfo], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnquiry' : ActorMethod<[string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];